name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run_test:
    name: Run 
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-11]
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install wheel
      run: python -m pip install --upgrade wheel
    - name: Install dependencies
      run: pip install -r ci/requirements.txt
    - name: Install solt
      run: pip install .
    - name: Run tests
      run: py.test tests --cov solt --cov-report term-missing -v
    - name: Run black
      run: black --config=black.toml --check .
    - name: Run flake8
      run: flake8
    - name: Run codecov
      run: codecov
      
